# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'git@192.168.0.201:IosGroup/TUYASpecRepo.git'
source 'https://github.com/CocoaPods/Specs.git' 

target '7-31testNull' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'WYNullView/Tool'
  pod "FXAudio"

  # Pods for 7-31testNull

  target '7-31testNullTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '7-31testNullUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
