# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UseLib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'PrivateLib',:path=> '../../Lib'

  # Pods for UseLib

  target 'UseLibTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UseLibUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
