# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LEDCalculator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 
pod 'Masonry' 
 
  # Pods for LEDCalculator

  target 'LEDCalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LEDCalculatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
