# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '9-23TestRecorder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 9-23TestRecorder

  target '9-23TestRecorderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '9-23TestRecorderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
