# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'SDWebImage', '~> 4.0.0-beta2'

target '1-22bannerTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 1-22bannerTest

  target '1-22bannerTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '1-22bannerTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
