# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '12-17test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # 上下拉刷新
  pod 'MJRefresh', '~> 3.1.12'

  # Pods for 12-17test

  target '12-17testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '12-17testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
