# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '12-09cocopodsTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # 忽略警告
  inhibit_all_warnings!
  # afn
  pod 'AFNetworking', '~> 3.1.0'
  # 刷新
  pod 'MJRefresh', '~> 3.1.12'

  # Pods for 12-09cocopodsTest

  target '12-09cocopodsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '12-09cocopodsTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
